name: CloudSim CI/CD with Dynamic Results

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-run-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Build and run simulation
      run: |
        mkdir -p lib
        wget -P lib/ https://downloads.sourceforge.net/project/cloudsim/3.0.3/cloudsim-3.0.3.jar
        javac -cp "lib/cloudsim-3.0.3.jar" -d bin src/org/cloudbus/cloudsim/*.java
        java -cp "bin:lib/cloudsim-3.0.3.jar" org.cloudbus.cloudsim.Main
        
    - name: Convert to CSV
      run: |
        mkdir -p results
        echo "CloudletID,VMID,Status,ExecTime,StartTime,FinishTime" > results/results.csv
        awk '/SUCCESS|FAILED/ {print $1","$2","$3","$4","$5","$6}' output.txt >> results/results.csv
        
    - name: Upload results artifact
      uses: actions/upload-artifact@v2
      with:
        name: simulation-results
        path: results/
        
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./results
        destination_dir: ./results
        keep_files: true